site:
  title: Spring IO Docs
  start_page: springio::index.adoc
content:
  sources:
# you should have cloned the repository https://github.com/markpollack/springio-refresh-doc
# into the following directory  
#  - url: ../springio-refresh-doc
  - url: https://github.com/markpollack/springio-refresh-doc

ui:
  bundle:
    url: ./resources/antora-ui-bundle.zip
# ui:
#   bundle:
#     url: https://github.com/rwinch/antora-ui-spring/releases/download/latest/ui-bundle.zip
#     snapshot: true    
